### ISSUE TITLE
Use JDK 1.6 and support other IDEs

### ISSUE THREAD

**Issue by krasa** [allotria/removeusage#1]
Apple folks still use it...  
Also you might want to set `since-build="129.000"`, it seems compatible with IJ 12.1 

And add  `<depends>com.intellij.modules.lang</depends>`  to allow all IDEs - see https://confluence.jetbrains.com/display/IDEADEV/Plugin+Compatibility+with+IntelliJ+Platform+Products

btw when I saw 'Remove Usage Plugin' I thought that it will remove some Usage plugin :-)

**Comment by allotria** [comment]
Well, Apple folks tend to upgrade their OS quite frequently and the current OS X 10.10 Yosemite does not come with Java any longer. Apple recommends to use Oracle Java 8 on Yosemite and later.

But sure, I'll look into it and go down to Java 6.

I'll allow prior versions of IntelliJ as well.

**Comment by allotria** [comment]
made plugin available to other supported products as well
