### ISSUE TITLE
Override the shortcut

### ISSUE THREAD

**Issue by krasa** [allotria/removeusage#2]
Context menu is not good enough imho, I would like to remove them just by pressing 'Del' key.

**Comment by allotria** [comment]
Yes, I tried to do that.
But somehow I couldn't get it to work right now.
I thought of overriding the shortcut for "EditorDeleteLine" or "SaveDelete" because "Delete" is used by the "Exclude" action.

**Comment by krasa** [comment]
Normally I would expect this to be enough, but for some reason it seems that it is registered before the original action:

```
<action id="UsageView.Exclude" overrides="true" text="Remove" class="ch.allotria.intellij.removeusage.action.RemoveUsageAction" use-shortcut-of="$Delete"/ >
```

I also tried to mangle with KeymapManagerEx to unregister the shortcut, without success, but maybe I did it wrong.

This heavy hack would work though:

```
        DefaultActionGroup usageViewPopup = (DefaultActionGroup) am.getAction("UsageView.Popup");
        am.unregisterAction("UsageView.Exclude");
        for (AnAction action : usageViewPopup.getChildActionsOrStubs()) {
            if (action instanceof ActionStub) {
                String className = ((ActionStub) action).getClassName();
                if (com.intellij.usages.actions.ExcludeUsageAction.class.getCanonicalName().equals(className)) {
                    usageViewPopup.remove(action);
                }
            }
        }

+

    <action id="UsageView.Delete" text="Remove" class="ch.allotria.intellij.removeusage.action.RemoveUsageAction" use-shortcut-of="$Delete" >
            <add-to-group group-id="UsageView.Popup" anchor="after" relative-to-action="UsageView.Include"/>
    </action>
```

**Comment by allotria** [comment]
Thanks a lot for your input.
I'll give it a try tonight.

**Comment by allotria** [comment]
Added a keyboard shortcut to the menu item (alt BACK_SPACE). 
I don't want to override the default behaviour for DELETE.

**Comment by krasa** [comment]
:+1:
